'use client'

import { useState, useCallback, useEffect } from 'react'
import { 
  Github, 
  Plus, 
  GitCommit, 
  Lock,
  Globe,
  Loader2,
  Check,
  AlertCircle,
  ExternalLink,
  FileCode,
  RefreshCw
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { 
  initGitHub, 
  getGitHubStatus, 
  createRepository, 
  commitFiles,
  isGitHubInitialized 
} from '@/lib/git-service'
import type { Project, ProjectFile } from '@/types/project'
import type { GitCommitRequest, GitRepoRequest, GitStatus, GitRepo } from '@/types/git'

export function GitPanel({ project, isVisible }: { project: Project | null; isVisible: boolean }) {
  const [token, setToken] = useState('')
  const [status, setStatus] = useState<GitStatus | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isConnecting, setIsConnecting] = useState(false)
  
  // Create repo form
  const [repoName, setRepoName] = useState('')
  const [repoDescription, setRepoDescription] = useState('')
  const [isPrivate, setIsPrivate] = useState(true)
  const [commitMessage, setCommitMessage] = useState('')
  
  // Results
  const [createdRepo, setCreatedRepo] = useState<{ repoUrl: string; cloneUrl: string } | null>(null)
  const [commitResult, setCommitResult] = useState<{ sha: string; url: string } | null>(null)
  const [error, setError] = useState<string | null>(null)
  
  // Check status on mount
  useEffect(() => {
    if (isVisible && isGitHubInitialized()) {
      checkStatus()
    }
  }, [isVisible])
  
  const checkStatus = useCallback(async () => {
    setIsLoading(true)
    const newStatus = await getGitHubStatus()
    setStatus(newStatus)
    setIsLoading(false)
  }, [])
  
  const connect = useCallback(async () => {
    if (!token.trim()) return
    
    setIsConnecting(true)
    setError(null)
    
    try {
      initGitHub(token)
      await checkStatus()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to connect')
    } finally {
      setIsConnecting(false)
    }
  }, [token, checkStatus])
  
  const createRepo = useCallback(async () => {
    if (!project || !repoName.trim()) return
    
    setIsLoading(true)
    setError(null)
    
    const files = project.files.map(f => ({
      path: f.path,
      content: f.content,
      operation: 'create' as const,
    }))
    
    const request: GitRepoRequest = {
      name: repoName,
      description: repoDescription || `Generated by AI App Builder: ${project.name}`,
      isPrivate,
      files,
    }
    
    const result = await createRepository(request)
    
    if (result.success && result.repoUrl) {
      setCreatedRepo({ repoUrl: result.repoUrl, cloneUrl: result.cloneUrl || '' })
    } else {
      setError(result.error || 'Failed to create repository')
    }
    
    setIsLoading(false)
  }, [project, repoName, repoDescription, isPrivate])
  
  const commit = useCallback(async () => {
    if (!project || !commitMessage.trim()) return
    
    setIsLoading(true)
    setError(null)
    
    const files = project.files.map(f => ({
      path: f.path,
      content: f.content,
      operation: 'update' as const,
    }))
    
    const request: GitCommitRequest = {
      message: commitMessage,
      files,
    }
    
    const result = await commitFiles(request)
    
    if (result.success && result.sha) {
      setCommitResult({ sha: result.sha, url: result.url || '' })
    } else {
      setError(result.error || 'Failed to commit')
    }
    
    setIsLoading(false)
  }, [project, commitMessage])
  
  if (!isVisible) return null
  
  return (
    <div className="flex flex-col h-full bg-zinc-900">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-700">
        <div className="flex items-center gap-2">
          <Github className="w-5 h-5 text-zinc-100" />
          <span className="font-medium text-zinc-100">Git Integration</span>
          {status?.isConnected && (
            <span className="flex items-center gap-1 text-xs px-2 py-0.5 bg-green-900/50 text-green-400 rounded">
              <Check className="w-3 h-3" />
              Connected
            </span>
          )}
        </div>
        {status?.isConnected && (
          <button
            onClick={checkStatus}
            disabled={isLoading}
            className="p-1.5 text-zinc-400 hover:text-zinc-200 rounded hover:bg-zinc-700 disabled:opacity-50"
          >
            <RefreshCw className={cn('w-4 h-4', isLoading && 'animate-spin')} />
          </button>
        )}
      </div>
      
      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {/* Auth Section */}
        {!status?.isConnected ? (
          <div className="space-y-4">
            <div className="p-4 bg-zinc-800 rounded-lg">
              <h3 className="text-sm font-medium text-zinc-200 mb-3">
                Connect to GitHub
              </h3>
              <p className="text-xs text-zinc-500 mb-4">
                Enter your personal access token with repo scope.
                <a 
                  href="https://github.com/settings/tokens"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ml-1 text-blue-400 hover:underline"
                >
                  Create token
                </a>
              </p>
              <div className="space-y-3">
                <input
                  type="password"
                  value={token}
                  onChange={(e) => setToken(e.target.value)}
                  placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                  className="w-full px-3 py-2 bg-zinc-900 text-zinc-100 text-sm rounded border border-zinc-700 focus:border-blue-500 focus:outline-none"
                />
                <button
                  onClick={connect}
                  disabled={!token.trim() || isConnecting}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-zinc-700 text-white text-sm rounded hover:bg-zinc-600 disabled:opacity-50"
                >
                  {isConnecting ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Connecting...
                    </>
                  ) : (
                    <>
                      <Github className="w-4 h-4" />
                      Connect
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        ) : (
          <>
            {/* User Info */}
            <div className="flex items-center gap-3 p-3 bg-zinc-800 rounded-lg">
              {status.avatarUrl && (
                <img 
                  src={status.avatarUrl} 
                  alt={status.username || ''}
                  className="w-10 h-10 rounded-full"
                />
              )}
              <div>
                <div className="text-sm font-medium text-zinc-200">{status.username}</div>
                <div className="text-xs text-zinc-500">{status.repos.length} repositories</div>
              </div>
            </div>
            
            {/* Create Repository */}
            <div className="p-4 bg-zinc-800 rounded-lg space-y-4">
              <h3 className="text-sm font-medium text-zinc-200 flex items-center gap-2">
                <Plus className="w-4 h-4" />
                Create New Repository
              </h3>
              
              <div className="space-y-3">
                <input
                  type="text"
                  value={repoName}
                  onChange={(e) => setRepoName(e.target.value)}
                  placeholder="Repository name"
                  className="w-full px-3 py-2 bg-zinc-900 text-zinc-100 text-sm rounded border border-zinc-700 focus:border-blue-500 focus:outline-none"
                />
                <input
                  type="text"
                  value={repoDescription}
                  onChange={(e) => setRepoDescription(e.target.value)}
                  placeholder="Description (optional)"
                  className="w-full px-3 py-2 bg-zinc-900 text-zinc-100 text-sm rounded border border-zinc-700 focus:border-blue-500 focus:outline-none"
                />
                <label className="flex items-center gap-2 text-sm text-zinc-400">
                  <input
                    type="checkbox"
                    checked={isPrivate}
                    onChange={(e) => setIsPrivate(e.target.checked)}
                    className="rounded border-zinc-600"
                  />
                  <Lock className="w-4 h-4" />
                  Private repository
                </label>
                <button
                  onClick={createRepo}
                  disabled={!repoName.trim() || !project || isLoading}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-green-700 text-white text-sm rounded hover:bg-green-600 disabled:opacity-50"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Creating...
                    </>
                  ) : (
                    <>
                      <Github className="w-4 h-4" />
                      Create & Push
                    </>
                  )}
                </button>
              </div>
            </div>
            
            {/* Commit to Existing */}
            <div className="p-4 bg-zinc-800 rounded-lg space-y-4">
              <h3 className="text-sm font-medium text-zinc-200 flex items-center gap-2">
                <GitCommit className="w-4 h-4" />
                Commit Changes
              </h3>
              
              <div className="space-y-3">
                <textarea
                  value={commitMessage}
                  onChange={(e) => setCommitMessage(e.target.value)}
                  placeholder="Commit message..."
                  className="w-full h-20 px-3 py-2 bg-zinc-900 text-zinc-100 text-sm rounded border border-zinc-700 focus:border-blue-500 focus:outline-none resize-none"
                />
                <button
                  onClick={commit}
                  disabled={!commitMessage.trim() || !project || isLoading}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-blue-700 text-white text-sm rounded hover:bg-blue-600 disabled:opacity-50"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Committing...
                    </>
                  ) : (
                    <>
                      <GitCommit className="w-4 h-4" />
                      Commit
                    </>
                  )}
                </button>
              </div>
            </div>
            
            {/* Repositories List */}
            <div className="space-y-2">
              <h3 className="text-sm font-medium text-zinc-400">Your Repositories</h3>
              <div className="space-y-1">
                {status.repos.slice(0, 10).map((repo) => (
                  <a
                    key={repo.id}
                    href={repo.htmlUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between p-3 bg-zinc-800 rounded-lg hover:bg-zinc-700 transition-colors group"
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      {repo.private ? (
                        <Lock className="w-4 h-4 text-amber-400 flex-shrink-0" />
                      ) : (
                        <Globe className="w-4 h-4 text-green-400 flex-shrink-0" />
                      )}
                      <span className="text-sm text-zinc-200 truncate">{repo.name}</span>
                    </div>
                    <ExternalLink className="w-4 h-4 text-zinc-500 opacity-0 group-hover:opacity-100" />
                  </a>
                ))}
              </div>
            </div>
          </>
        )}
        
        {/* Results */}
        {createdRepo && (
          <div className="p-4 bg-green-900/20 border border-green-700 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Check className="w-5 h-5 text-green-400" />
              <span className="text-sm font-medium text-green-400">
                Repository Created!
              </span>
            </div>
            <a 
              href={createdRepo.repoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-blue-400 hover:underline"
            >
              {createdRepo.repoUrl}
            </a>
          </div>
        )}
        
        {commitResult && (
          <div className="p-4 bg-blue-900/20 border border-blue-700 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Check className="w-5 h-5 text-blue-400" />
              <span className="text-sm font-medium text-blue-400">
                Committed Successfully
              </span>
            </div>
            <code className="text-xs text-zinc-500 font-mono">
              {commitResult.sha.slice(0, 7)}
            </code>
          </div>
        )}
        
        {/* Error */}
        {error && (
          <div className="flex items-start gap-2 p-3 bg-red-900/30 border border-red-700 rounded-lg">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <span className="text-sm text-red-200">{error}</span>
          </div>
        )}
      </div>
    </div>
  )
}