import JSZip from 'jszip'
import type { 
  Project, 
  ExportFormat, 
  ExportResult, 
  ExportOptions,
  ZipExportResult,
  VercelDeployConfig,
  VercelDeployResult 
} from '@/types/export'

export async function exportAsZip(
  project: Project,
  options?: ExportOptions
): Promise<ZipExportResult> {
  try {
    const zip = new JSZip()
    
    // Create folder structure
    const rootFolder = zip.folder(project.name)
    if (!rootFolder) {
      throw new Error('Failed to create root folder')
    }
    
    // Add files to zip
    project.files.forEach(file => {
      const path = file.path.startsWith('/') ? file.path.slice(1) : file.path
      const parts = path.split('/')
      
      if (parts.length === 1) {
        rootFolder.file(parts[0], file.content)
      } else {
        let currentFolder = rootFolder
        for (let i = 0; i < parts.length - 1; i++) {
          const folderName = parts[i]
          const existingFolder = currentFolder.folder(folderName)
          currentFolder = existingFolder || currentFolder
        }
        currentFolder.file(parts[parts.length - 1], file.content)
      }
    })
    
    // Generate README
    const readme = generateReadme(project)
    rootFolder.file('README.md', readme)
    
    // Generate package.json if not present
    const hasPackageJson = project.files.some(f => f.name === 'package.json')
    if (!hasPackageJson) {
      const packageJson = generatePackageJson(project)
      rootFolder.file('package.json', JSON.stringify(packageJson, null, 2))
    }
    
    // Generate blob
    const blob = await zip.generateAsync({ type: 'blob' })
    
    return {
      success: true,
      logs: [] as string[],
      blob,
      filename: `${project.name}.zip`,
      error: null,
    }
  } catch (error) {
    return {
      success: false,
      logs: [] as string[],
      blob: null,
      filename: `${project.name}.zip`,
      error: error instanceof Error ? error.message : 'Failed to create ZIP',
    }
  }
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export async function deployToVercel(
  config: VercelDeployConfig
): Promise<VercelDeployResult> {
  const token = process.env.VERCEL_TOKEN
  
  if (!token) {
    return {
      success: false,
      logs: [] as string[],
      deploymentUrl: null,
      projectUrl: null,
      error: 'Vercel token not configured',
    }
  }
  
  try {
    const response = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: config.projectName,
        files: Object.entries(config.files).map(([file, content]) => ({
          file,
          data: Buffer.from(content).toString('base64'),
          encoding: 'base64',
        })),
        framework: config.framework,
        target: 'production',
        ...(config.buildCommand && { build: { env: {} } }),
      }),
    })
    
    const data = await response.json()
    
    if (!response.ok) {
      throw new Error(data.error?.message || 'Deployment failed')
    }
    
    return {
      success: true,
      logs: [] as string[],
      deploymentUrl: `https://${data.url}`,
      projectUrl: data.project?.url || null,
      error: null,
    }
  } catch (error) {
    return {
      success: false,
      logs: [] as string[],
      deploymentUrl: null,
      projectUrl: null,
      error: error instanceof Error ? error.message : 'Deployment failed',
    }
  }
}

function generateReadme(project: Project): string {
  return `# ${project.name}

${project.description || 'Generated by AI App Builder'}

## Project Structure

${project.files.map(f => `- \`${f.path}\``).join('\n')}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Files

| File | Type | Description |
|------|------|-------------|
${project.files.map(f => `| ${f.path} | ${f.type} | ${f.language} |`).join('\n')}

---
Generated by [AI App Builder](https://ai-app-builder.vercel.app)
`
}

function generatePackageJson(project: Project): object {
  const hasReact = project.files.some(f => 
    f.language === 'typescript' && f.content.includes('React')
  )
  const hasNext = project.files.some(f => f.path.includes('next'))
  
  if (hasNext) {
    return {
      name: project.name.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.0.0',
        'react-dom': '^18.0.0',
      },
      devDependencies: {
        '@types/node': '^20',
        '@types/react': '^18',
        typescript: '^5',
      },
    }
  }
  
  if (hasReact) {
    return {
      name: project.name.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^18.0.0',
        'react-dom': '^18.0.0',
      },
      devDependencies: {
        '@types/react': '^18.0.0',
        '@types/react-dom': '^18.0.0',
        '@vitejs/plugin-react': '^4.0.0',
        typescript: '^5.0.0',
        vite: '^5.0.0',
      },
    }
  }
  
  return {
    name: project.name.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'npx serve .',
    },
    devDependencies: {
      serve: '^14.0.0',
    },
  }
}